sudo: false
language: node_js
node_js:
    - "0.10"
    - "0.11"
    - "0.12"
    - "iojs-v2.5.0"
env:
    - TEST_SUITE=coveralls
    - TEST_SUITE=lint
    - TEST_SUITE=unit
script: "npm run-script $TEST_SUITE"
