import { Component } from 'react';

export class AccessingInternals extends Component {}
export class ControlledMenu extends Component {}
export class AnimatedMulti extends Component {}
export class AsyncCallbacks extends Component {}
export class AsyncCreatable extends Component {}
export class AsyncPromises extends Component {}
export class BasicGrouped extends Component {}
export class BasicMulti extends Component {}
export class BasicSingle extends Component {}
export class CustomControl extends Component {}
export class CreatableAdvanced extends Component {}
export class CreatableInputOnly extends Component {}
export class CreateFilter extends Component {}
export class CreatableMulti extends Component {}
export class CreatableSingle extends Component {}
export class CustomSelectProps extends Component {}
export class CustomClearIndicator extends Component {}
export class CustomDropdownIndicator extends Component {}
export class CustomLoadingIndicator extends Component {}
export class CustomLoadingMessage extends Component {}
export class CustomGroup extends Component {}
export class CustomMenu extends Component {}
export class CustomMenuList extends Component {}
export class CustomIndicatorsContainer extends Component {}
export class CustomIndicatorSeparator extends Component {}
export class CustomNoOptionsMessage extends Component {}
export class CustomMultiValueContainer extends Component {}
export class CustomOption extends Component {}
export class CustomMultiValueLabel extends Component {}
export class CustomMultiValueRemove extends Component {}
export class CustomInput extends Component {}
export class CustomGroupHeading extends Component {}
export class CustomPlaceholder extends Component {}
export class CustomSelectContainer extends Component {}
export class CustomSingleValue extends Component {}
export class CustomValueContainer extends Component {}
export class CustomGetOptionLabel extends Component {}
export class CustomGetOptionValue extends Component {}
export class CustomFilterOptions extends Component {}
export class CustomIsOptionDisabled extends Component {}
export class DefaultOptions extends Component {}
export class Experimental extends Component {}
export class FixedOptions extends Component {}
export class MultiSelectSort extends Component {}
export class Popout extends Component {}
export class StyledMulti extends Component {}
export class StyledSingle extends Component {}
export class OnSelectResetsInput extends Component {}
export class AsyncMulti extends Component {}
export class MenuBuffer extends Component {}
export class MenuPortal extends Component {}
export class Theme extends Component {}
export class StyleCompositionExample extends Component {}
